name: hyper
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/dstaley/hyper
author: Dylan Staley <staley.dylan@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  build: ^1.0.2
  build_runner: ^1.1.2
  code_builder: ^3.1.3
  dart_style: ^1.2.2
  source_gen: ^0.9.3
  test: ^1.0.0
